version: "3"

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.2
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker

    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  ghost:
    # A container that exposes ghost blog 
    image: ghost
    labels:
      - "traefik.http.routers.ghost.rule=Host(`ghost.letsbuilditinthecloud.com`)"
  nginx:
    # A container that exposes ngnix container for react
    image: nginx
    labels:
      - "traefik.http.routers.nginx.rule=Host(`nginx.letsbuilditinthecloud.com`)"
  jenkins:
    # A container that exposes jenkins for oir pipeline
    image: jenkins
    labels:
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.letsbuilditinthecloud.com`)"
